#!/usr/bin/env bash
# install Nginx with init file with the message "Hello World"

sudo apt -y update
sudo apt -y install nginx
ufw allow "Nginx HTTP"
echo "Hello World!" > /var/www/html/index.nginx-debian.html
sudo service nginx start
