#!/usr/bin/env bash
# install Nginx with init file with the message "Hello World"

sudo apt update -y
sudo apt upgrade -y
sudo apt install nginx -y
sudo service nginx start
ufw allow "Nginx HTTP"
echo "Hello World!" > /var/www/html/index.nginx-debian.html
sudo service restart
