#!/usr/bin/env bash
# install Nginx with init file with the message "Hello World"

sudo apt-get -y update
sudo apt-get -y install nginx
ufw allow "Nginx HTTP"
echo "Hello World!" > /var/www/html/index.html
sudo service nginx start
