#!/usr/bin/env bash
# This script prints "bad luck" in forth line
# "good luck" in eighth line
# else prints "Best School"

i=1
while [ $i -lt 9 ]
do
	if [ $i -eq 4 ]
	then
		echo "bad luck"
	elif [ $i -eq 7 ]
	then
		echo "good luck"
	fi
	echo "Best School"
	(( i++ ))
done
