#!/usr/bin/env bash
# This script prints 1 to 20
#	"bad luck from China" after 5
#	"bad luck from Japan" after 9
#	"bad luck from Italy" after 17

i=1
while [ $i -le 20 ]
do
	echo "$i"
	case $i in
		"4") echo "bad luck from China";;
		"9") echo "bad luck from Japan";;
		"17") echo "bad luck from Italy";;
	esac
	(( i++ ))
done
