#!/usr/bin/env bash
# Script that displays the content of the current directory
#	in a list format
#	where only the part of the name is displayed

lis=$(ls)
for i in $lis
do
	echo "$i" | cut -d '-' -f2
done
